import Head from 'next/head'
import ProtectedRoute from '../utils/ProtectedRoute'
import { useAuth } from '../utils/contexts/AuthContext'

interface ProtectedLayoutProps {
  children: React.ReactNode
}

export default function ProtectedLayout({ children }: ProtectedLayoutProps) {
  const { loading } = useAuth()

  if (loading) null

  return (
    <ProtectedRoute>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{children}</main>
    </ProtectedRoute>
  )
}
